// Flat dot-key dictionary, EN/ES. Values may carry **bold** or `code`
// markup for the handful of strings with inline emphasis -- see the <T>
// component in i18n.jsx, which is the only thing that parses it. Plain
// t() calls (buttons, labels, aria) never need markup, so most values
// below are bare strings.
//
// Not translated on purpose: document/file names (trust-deed-aurora.pdf),
// proper/legal names (Grupo Meridian, S.A.S.), the Spanish source
// quotations in results.issue.*, model names, and "palimpsest" itself.
export const STRINGS = {
  en: {
    "common.chooseFiles": "Choose files",
    "common.back": "← Back",
    "common.cancel": "Cancel",
    "common.undo": "Undo",
    "common.step1": "Step 1 of 3",
    "common.step2": "Step 2 of 3",
    "common.step3": "Step 3 of 3",

    "app.toggleSettings": "Toggle settings",
    "app.brandAria": "Go to overview",
    "app.showSidebar": "Show sidebar",
    "app.backendUnreachable": "Couldn't reach the server",

    "theme.toggle": "Toggle color theme",

    "lang.switchTo": "Switch to {lang}",
    "lang.english": "English",
    "lang.spanish": "Spanish",

    "zoom.out": "Zoom out",
    "zoom.in": "Zoom in",
    "zoom.reset": "Reset zoom",

    "wipe.aria": "Compare original and translated page",
    "wipe.source": "source",
    "wipe.translated": "translated",

    "rail.backend": "Backend",
    "rail.hideSidebar": "Hide sidebar",
    "rail.protectedEntities": "Protected entities",
    "rail.group.companies": "Companies",
    "rail.group.people": "People",
    "rail.group.places": "Places",
    "rail.group.other": "Other",
    "rail.dropHere": "drop here",
    "rail.moveTo": "Move to {group}",
    "rail.addPlaceholder": "Add a name, press Enter...",
    "rail.add": "Add",
    "rail.removeAria": "Remove {value}",
    "rail.caseNote": "Case and accent variants are generated for you -- add `Banco Litoral`, not `Banco Litoral` and `BANCO LITORAL` separately.",
    "rail.importToml": "Import .toml",
    "rail.exportToml": "Export .toml",
    "rail.importNotice": "Prototype only -- the real build parses a dropped .toml in the same shape as private/entities.toml.",
    "rail.suggested": "Suggested, from the document",
    "rail.suggestedNote": "Capitalized phrases found in the document that aren't protected yet. Nothing here is applied automatically.",

    "backend.apiKeyLabel": "API key",
    "backend.check": "Check",
    "backend.status.idle": "Not checked yet",
    "backend.status.checking": "Checking...",
    "backend.status.ok": "Key works -- gemini-3.5-flash-lite reachable",
    "backend.status.empty": "Enter a key first",
    "backend.keyNote": "Held for this browser session and sent to your own local server only -- never written to disk, never sent anywhere but the backend you picked.",
    "backend.getKey": "Get a free Gemini key ↗",
    "backend.keyDetected": "detected",
    "backend.keyMissing": "not set -- export it and restart the server",
    "backend.keyServerNote": "Read from the server's own environment only -- never typed into the browser or sent over the network.",
    "backend.sub.gemini": "Free tier - needs a free API key",
    "backend.sub.anthropic": "Paid - best quality on legal & financial prose",
    "backend.sub.google": "Free - no key - no entity or glossary awareness",

    "compare.back": "← Back to results",
    "compare.prevAria": "Previous page",
    "compare.nextAria": "Next page",
    "compare.page": "page {n} of 4",
    "compare.compare": "Compare",
    "compare.edit": "Edit",
    "compare.fixtureNote": "The sample fixture covers page 1 only -- page navigation above is cosmetic in this prototype.",
    "compare.loadingLayout": "Loading page layout...",

    "overview.eyebrow": "How it works",
    "overview.title": "Documents, translated in place.",
    "overview.body": "palimpsest translates PDFs and Office files without rebuilding them -- same pages, same fonts, same artwork, only the words change. Anything you list as protected, a company name, a person, an amount, stays exactly as written.",
    "overview.step1": "**Pick a backend.** Gemini's free tier needs only an API key, no billing setup -- see the sidebar.",
    "overview.step2": "**Name what must survive verbatim.** Company names, people, places -- added once, protected everywhere.",
    "overview.step3": "**Drop a file.** PDF, Word, PowerPoint, or Excel -- you get back a replica, plus an honest report of anything that didn't translate.",
    "overview.cta": "See a sample →",
    "overview.dropTitle": "Or drop a file here to start now",
    "overview.dropExts": ".pdf · .docx · .pptx · .xlsx",

    "sample.caption": "drag, or use ← → -- Aurora Plaza Trust, sample deed, 1 of 1",
    "sample.dropTitle": "Drop files here, or click to browse",
    "sample.dropSub": ".pdf · .docx · .pptx · .xlsx -- dropped anywhere on this page",
    "sample.altOut": "Translated sample page (English)",
    "sample.altSrc": "Original sample page (Spanish)",

    "queue.title": "Queue",
    "queue.body": "Classified before anything is sent anywhere -- a scan means an OCR pass, which is the slow part.",
    "queue.kind.digital": "digital",
    "queue.kind.scan": "scan",
    "queue.kind.ocr": "OCR text layer",
    "queue.kind.office": "office document",
    "queue.pagesUnit": "{n} pages",
    "queue.removeAria": "Remove {name}",
    "queue.scanAlert": "**{name}** is a scan -- it needs OCR before translation, which runs as an external process and can take several minutes with no way to interrupt it once started.",
    "queue.cta": "Estimate cost →",

    "estimate.title": "Before anything is spent",
    "estimate.body": "Nothing is sent to a translation backend until you confirm here.",
    "estimate.paragraphs": "Paragraphs",
    "estimate.uniqueStrings": "{n} unique strings",
    "estimate.cacheHits": "Cache hits",
    "estimate.cacheSub": "0% -- first run of this document",
    "estimate.tokens": "Tokens (est.)",
    "estimate.in": "in",
    "estimate.out": "out",
    "estimate.cost": "Cost",
    "estimate.costSub": "estimated, not exact",
    "estimate.costUnknown": "unknown",
    "estimate.note": "Cost shown as unknown, not $0.00, whenever the backend can't price the request -- Google Translate is free by design, not free by omission.",
    "estimate.cta": "Translate {n} documents →",
    "estimate.ctaSingular": "Translate {n} document →",

    "running.title": "Running",
    "running.phase.classify.name": "Classify",
    "running.phase.classify.detail": "digital text layer found",
    "running.phase.ocr.name": "OCR",
    "running.phase.ocr.detail": "skipped -- not a scan",
    "running.phase.extract.name": "Extract",
    "running.phase.extract.detail": "172 paragraphs found across 4 pages",
    "running.phase.translate.name": "Translate",
    "running.phase.render.name": "Render",
    "running.phase.render.detail": "waiting",
    "running.phase.save.name": "Save",
    "running.phase.save.detail": "waiting",
    "running.translateProgress": "{count} of 154 unique strings",
    "running.translateProgressReal": "{count} of {total} unique strings",
    "running.footer": "document 1 of 2 · {pct}% of this document",
    "running.footerReal": "document {i} of {n} · {pct}% of this document",
    "running.waiting": "waiting",
    "running.connectionLost": "Lost the connection to the server while running -- the job may still be in progress.",
    "running.cancelNote": "Cancelling abandons the result -- an in-flight OCR or translation call can't be interrupted mid-request, only left to finish and discarded.",

    "results.titleRest": "of {total} paragraphs translated.",
    "results.newTranslation": "New translation",
    "results.stat.translated": "Translated",
    "results.stat.skippedProtected": "Kept Spanish - protected",
    "results.stat.failed": "Failed",
    "results.stat.refused": "Refused",
    "results.stat.identical": "Identical",
    "results.subtitle1": "What didn't translate",
    "results.status.failed": "failed",
    "results.status.refused": "refused",
    "results.status.skipped": "skipped · protected",
    "results.issue.failed1": "page 2 - entity/number assertion failed twice",
    "results.issue.refused1": "page 3 - model declined to answer",
    "results.issue.failed2": "page 1 - digit-sequence mismatch after retry",
    "results.issue.skipped1": "page 1 - matches a protected entity, left untouched by design",
    "results.viewOnPage": "View on page →",
    "results.noIssues": "Nothing to report -- every paragraph translated cleanly.",
    "results.subtitle2": "Font substitutions",
    "results.fontSubCount": "{count} paragraphs",
    "results.download.replica.title": "Replica",
    "results.download.replica.sub": "trust-deed-aurora.en.pdf",
    "results.download.dual.title": "Dual PDF",
    "results.download.dual.sub": "source + translated, interleaved",
    "results.download.report.title": "Report",
    "results.download.report.sub": "trust-deed-aurora.report.json",
    "results.downloadNotice": "Prototype only -- would download {file}",

    "edit.deleteParagraph": "Delete paragraph",
    "edit.paragraphLabel": "Paragraph {n}",
    "edit.editingSuffix": " - editing text",
    "edit.noneSelected": "No paragraph selected",
    "edit.paragraphAria": "Paragraph {n} of {total}, page 1",
    "edit.unsavedCount": "{n} unsaved edit",
    "edit.unsavedCountPlural": "{n} unsaved edits",
    "edit.noUnsaved": "No unsaved edits",
    "edit.discard": "Discard edits",
    "edit.download": "Download edits (JSON)",
    "edit.discardNotice": "All edits discarded.",
    "edit.exportNotice": "Prototype only -- the real build PATCHes this to /api/jobs/{id}/layout.",
    "edit.exportNoticeReal": "Saved -- the PDF has been regenerated with your edits.",
    "edit.deleteNotice": "Paragraph removed -- undoable below.",
    "edit.restoreNotice": "Paragraph restored.",
    "edit.restore": "removed - click to restore",
    "edit.capacity.overflow": "will overflow -- the server draws it anyway",
    "edit.capacity.shrunk": "will shrink to {size}pt (from {from}pt)",
    "edit.capacity.fits": "fits - {n} line",
    "edit.capacity.fitsPlural": "fits - {n} lines",
    "edit.capacity.estimatedSuffix": " - estimated",
  },
  es: {
    "common.chooseFiles": "Elegir archivos",
    "common.back": "← Volver",
    "common.cancel": "Cancelar",
    "common.undo": "Deshacer",
    "common.step1": "Paso 1 de 3",
    "common.step2": "Paso 2 de 3",
    "common.step3": "Paso 3 de 3",

    "app.toggleSettings": "Alternar ajustes",
    "app.brandAria": "Ir al resumen",
    "app.showSidebar": "Mostrar barra lateral",
    "app.backendUnreachable": "No se pudo conectar con el servidor",

    "theme.toggle": "Cambiar tema de color",

    "lang.switchTo": "Cambiar a {lang}",
    "lang.english": "inglés",
    "lang.spanish": "español",

    "zoom.out": "Alejar",
    "zoom.in": "Acercar",
    "zoom.reset": "Restablecer zoom",

    "wipe.aria": "Comparar la página original y la traducida",
    "wipe.source": "original",
    "wipe.translated": "traducido",

    "rail.backend": "Backend",
    "rail.hideSidebar": "Ocultar barra lateral",
    "rail.protectedEntities": "Entidades protegidas",
    "rail.group.companies": "Empresas",
    "rail.group.people": "Personas",
    "rail.group.places": "Lugares",
    "rail.group.other": "Otros",
    "rail.dropHere": "soltar aquí",
    "rail.moveTo": "Mover a {group}",
    "rail.addPlaceholder": "Agrega un nombre y presiona Enter...",
    "rail.add": "Agregar",
    "rail.removeAria": "Quitar {value}",
    "rail.caseNote": "Las variantes de mayúsculas y acentos se generan automáticamente -- agrega `Banco Litoral`, no `Banco Litoral` y `BANCO LITORAL` por separado.",
    "rail.importToml": "Importar .toml",
    "rail.exportToml": "Exportar .toml",
    "rail.importNotice": "Solo prototipo -- la versión real analiza un .toml soltado con la misma forma que private/entities.toml.",
    "rail.suggested": "Sugerido, del documento",
    "rail.suggestedNote": "Frases con mayúscula inicial encontradas en el documento que aún no están protegidas. Nada aquí se aplica automáticamente.",

    "backend.apiKeyLabel": "Clave de API",
    "backend.check": "Verificar",
    "backend.status.idle": "Aún no verificada",
    "backend.status.checking": "Verificando...",
    "backend.status.ok": "La clave funciona -- gemini-3.5-flash-lite accesible",
    "backend.status.empty": "Primero ingresa una clave",
    "backend.keyNote": "Se guarda solo durante esta sesión del navegador y se envía únicamente a tu propio servidor local -- nunca se escribe en disco ni se envía a otro lugar que no sea el backend elegido.",
    "backend.getKey": "Obtener una clave gratuita de Gemini ↗",
    "backend.keyDetected": "detectada",
    "backend.keyMissing": "no configurada -- expórtala y reinicia el servidor",
    "backend.keyServerNote": "Se lee únicamente del entorno del servidor -- nunca se escribe en el navegador ni se envía por la red.",
    "backend.sub.gemini": "Nivel gratuito - requiere una clave de API gratuita",
    "backend.sub.anthropic": "De pago - mejor calidad en prosa legal y financiera",
    "backend.sub.google": "Gratis - sin clave - sin reconocimiento de entidades ni glosario",

    "compare.back": "← Volver a resultados",
    "compare.prevAria": "Página anterior",
    "compare.nextAria": "Página siguiente",
    "compare.page": "página {n} de 4",
    "compare.compare": "Comparar",
    "compare.edit": "Editar",
    "compare.fixtureNote": "La muestra de prueba solo cubre la página 1 -- la navegación de páginas de arriba es solo decorativa en este prototipo.",
    "compare.loadingLayout": "Cargando el diseño de la página...",

    "overview.eyebrow": "Cómo funciona",
    "overview.title": "Documentos, traducidos en el mismo lugar.",
    "overview.body": "palimpsest traduce PDFs y archivos de Office sin reconstruirlos -- las mismas páginas, las mismas fuentes, el mismo arte, solo cambian las palabras. Todo lo que marques como protegido, un nombre de empresa, una persona, un monto, se mantiene exactamente como está escrito.",
    "overview.step1": "**Elige un backend.** El nivel gratuito de Gemini solo necesita una clave de API, sin configurar facturación -- consulta la barra lateral.",
    "overview.step2": "**Nombra lo que debe permanecer intacto.** Nombres de empresas, personas, lugares -- se agregan una vez y quedan protegidos en todas partes.",
    "overview.step3": "**Suelta un archivo.** PDF, Word, PowerPoint o Excel -- obtienes una réplica, más un informe honesto de todo lo que no se tradujo.",
    "overview.cta": "Ver una muestra →",
    "overview.dropTitle": "O suelta un archivo aquí para empezar ahora",
    "overview.dropExts": ".pdf · .docx · .pptx · .xlsx",

    "sample.caption": "arrastra, o usa ← → -- Fideicomiso Aurora Plaza, escritura de muestra, 1 de 1",
    "sample.dropTitle": "Suelta archivos aquí, o haz clic para buscar",
    "sample.dropSub": ".pdf · .docx · .pptx · .xlsx -- soltado en cualquier parte de esta página",
    "sample.altOut": "Página de muestra traducida (inglés)",
    "sample.altSrc": "Página de muestra original (español)",

    "queue.title": "Cola",
    "queue.body": "Clasificado antes de enviar nada a ningún lado -- un escaneo implica un paso de OCR, que es la parte lenta.",
    "queue.kind.digital": "digital",
    "queue.kind.scan": "escaneo",
    "queue.kind.ocr": "capa de texto OCR",
    "queue.kind.office": "documento de office",
    "queue.pagesUnit": "{n} páginas",
    "queue.removeAria": "Quitar {name}",
    "queue.scanAlert": "**{name}** es un escaneo -- necesita OCR antes de traducirse, lo cual se ejecuta como un proceso externo y puede tardar varios minutos sin forma de interrumpirlo una vez iniciado.",
    "queue.cta": "Estimar costo →",

    "estimate.title": "Antes de gastar nada",
    "estimate.body": "Nada se envía a un backend de traducción hasta que confirmes aquí.",
    "estimate.paragraphs": "Párrafos",
    "estimate.uniqueStrings": "{n} cadenas únicas",
    "estimate.cacheHits": "Aciertos de caché",
    "estimate.cacheSub": "0% -- primera ejecución de este documento",
    "estimate.tokens": "Tokens (est.)",
    "estimate.in": "entrada",
    "estimate.out": "salida",
    "estimate.cost": "Costo",
    "estimate.costSub": "estimado, no exacto",
    "estimate.costUnknown": "desconocido",
    "estimate.note": "El costo se muestra como desconocido, no $0.00, cuando el backend no puede calcular el precio de la solicitud -- Google Translate es gratis por diseño, no gratis por omisión.",
    "estimate.cta": "Traducir {n} documentos →",
    "estimate.ctaSingular": "Traducir {n} documento →",

    "running.title": "En proceso",
    "running.phase.classify.name": "Clasificar",
    "running.phase.classify.detail": "se encontró capa de texto digital",
    "running.phase.ocr.name": "OCR",
    "running.phase.ocr.detail": "omitido -- no es un escaneo",
    "running.phase.extract.name": "Extraer",
    "running.phase.extract.detail": "172 párrafos encontrados en 4 páginas",
    "running.phase.translate.name": "Traducir",
    "running.phase.render.name": "Renderizar",
    "running.phase.render.detail": "esperando",
    "running.phase.save.name": "Guardar",
    "running.phase.save.detail": "esperando",
    "running.translateProgress": "{count} de 154 cadenas únicas",
    "running.translateProgressReal": "{count} de {total} cadenas únicas",
    "running.footer": "documento 1 de 2 · {pct}% de este documento",
    "running.footerReal": "documento {i} de {n} · {pct}% de este documento",
    "running.waiting": "esperando",
    "running.connectionLost": "Se perdió la conexión con el servidor durante el proceso -- el trabajo podría seguir en curso.",
    "running.cancelNote": "Cancelar descarta el resultado -- una llamada de OCR o traducción en curso no se puede interrumpir a mitad de camino, solo se deja terminar y se descarta.",

    "results.titleRest": "de {total} párrafos traducidos.",
    "results.newTranslation": "Nueva traducción",
    "results.stat.translated": "Traducidos",
    "results.stat.skippedProtected": "Se mantuvo en español - protegido",
    "results.stat.failed": "Fallidos",
    "results.stat.refused": "Rechazados",
    "results.stat.identical": "Idénticos",
    "results.subtitle1": "Lo que no se tradujo",
    "results.status.failed": "fallido",
    "results.status.refused": "rechazado",
    "results.status.skipped": "omitido · protegido",
    "results.issue.failed1": "página 2 - la verificación de entidad/número falló dos veces",
    "results.issue.refused1": "página 3 - el modelo se negó a responder",
    "results.issue.failed2": "página 1 - discrepancia en la secuencia de dígitos tras reintentar",
    "results.issue.skipped1": "página 1 - coincide con una entidad protegida, dejada intacta a propósito",
    "results.viewOnPage": "Ver en la página →",
    "results.noIssues": "Nada que informar -- todos los párrafos se tradujeron sin problemas.",
    "results.subtitle2": "Sustituciones de fuente",
    "results.fontSubCount": "{count} párrafos",
    "results.download.replica.title": "Réplica",
    "results.download.replica.sub": "trust-deed-aurora.en.pdf",
    "results.download.dual.title": "PDF dual",
    "results.download.dual.sub": "original + traducido, intercalados",
    "results.download.report.title": "Informe",
    "results.download.report.sub": "trust-deed-aurora.report.json",
    "results.downloadNotice": "Solo prototipo -- descargaría {file}",

    "edit.deleteParagraph": "Eliminar párrafo",
    "edit.paragraphLabel": "Párrafo {n}",
    "edit.editingSuffix": " - editando texto",
    "edit.noneSelected": "Ningún párrafo seleccionado",
    "edit.paragraphAria": "Párrafo {n} de {total}, página 1",
    "edit.unsavedCount": "{n} edición sin guardar",
    "edit.unsavedCountPlural": "{n} ediciones sin guardar",
    "edit.noUnsaved": "Sin ediciones pendientes",
    "edit.discard": "Descartar ediciones",
    "edit.download": "Descargar ediciones (JSON)",
    "edit.discardNotice": "Todas las ediciones fueron descartadas.",
    "edit.exportNotice": "Solo prototipo -- la versión real hace PATCH a /api/jobs/{id}/layout.",
    "edit.exportNoticeReal": "Guardado -- el PDF fue regenerado con tus ediciones.",
    "edit.deleteNotice": "Párrafo eliminado -- se puede deshacer abajo.",
    "edit.restoreNotice": "Párrafo restaurado.",
    "edit.restore": "eliminado - clic para restaurar",
    "edit.capacity.overflow": "desbordará -- el servidor lo dibuja de todas formas",
    "edit.capacity.shrunk": "se reducirá a {size}pt (desde {from}pt)",
    "edit.capacity.fits": "cabe - {n} línea",
    "edit.capacity.fitsPlural": "cabe - {n} líneas",
    "edit.capacity.estimatedSuffix": " - estimado",
  },
};
