// Flat dot-key dictionary, EN/ES. Values may carry **bold** or `code`
// markup for the handful of strings with inline emphasis -- see the <T>
// component in i18n.jsx, which is the only thing that parses it. Plain
// t() calls (buttons, labels, aria) never need markup, so most values
// below are bare strings.
//
// Not translated on purpose: document/file names (trust-deed-aurora.pdf),
// proper/legal names (Grupo Meridian, S.A.S.), the Spanish source
// quotations in results.issue.*, model names, and "palimpsest" itself.
export const STRINGS = {
  en: {
    "common.chooseFiles": "Choose files",
    "common.back": "← Back",
    "common.cancel": "Cancel",
    "common.undo": "Undo",
    "common.step1": "Step 1 of 3",
    "common.step2": "Step 2 of 3",
    "common.step3": "Step 3 of 3",

    "app.toggleSettings": "Toggle settings",
    "app.brandAria": "Go to overview",
    "app.showSidebar": "Show sidebar",
    "app.backendUnreachable": "Couldn't reach the server",
    "app.serverUnreachableBody": "No local server is answering at the address in the sidebar. Start one with `{cmd}`.",
    "app.setupHintTitle": "Set up a backend first",
    "app.setupHintBody": "No server is reachable yet. Open the sidebar and pick a backend -- Gemini's free tier just needs an API key, no billing required -- then try again.",

    "app.setupLink": "Setup instructions →",

    "footer.github": "GitHub ↗",
    "footer.pypi": "PyPI ↗",
    "footer.license": "Apache 2.0 ↗",

    "setup.back": "← Back to home",
    "setup.eyebrow": "Setup guide",
    "setup.title": "Get palimpsest running in four steps.",
    "setup.intro": "palimpsest runs on your own computer, so your documents never leave it except to the translation service you pick. That means a few minutes of one-time setup. Do these once and you're done.",
    "setup.copy": "Copy",
    "setup.copied": "Copied",
    "setup.s1.title": "Install Python 3.11 or newer",
    "setup.s1.body": "Check what you have by running `python --version`. On Windows, tick **Add Python to PATH** in the installer -- most \"command not found\" problems trace back to skipping it.",
    "setup.s1.link": "Download Python ↗",
    "setup.s2.title": "Install palimpsest",
    "setup.s2.body": "Open a terminal (Command Prompt, PowerShell, or Terminal) and run this. It installs the server and the free Gemini backend.",
    "setup.s3.title": "Start the local server",
    "setup.s3.body": "Run this and **leave the window open** -- it is the server. Closing it stops palimpsest.",
    "setup.s3.note": "It listens on http://127.0.0.1:8765, reachable only from your own computer.",
    "setup.s4.title": "Add a free Gemini key",
    "setup.s4.body": "Get a free key from Google AI Studio (no billing, no card), then paste it into the **API key** box in this page's sidebar and press Save.",
    "setup.check.title": "Is it working?",
    "setup.check.idle": "Once the server is running, check the connection from here.",
    "setup.check.ok": "Connected -- the server is answering. You're ready to translate.",
    "setup.check.fail": "Still can't reach it. Make sure the server window from step 3 is open, then check again.",
    "setup.check.btn": "Check connection",
    "setup.opt.title": "Optional extras",
    "setup.opt.intro": "None of these are needed for a first translation. Add them when you hit the situation they solve.",
    "setup.opt.ocr.q": "Translating scanned PDFs",
    "setup.opt.ocr.a": "Scans have no text to read, so palimpsest runs OCR first. Install the extra below, plus **Tesseract** with the language data for your documents (`spa` for Spanish, `eng` for English), and make sure `tesseract` is on your PATH.",
    "setup.opt.office.q": "Previewing Word, PowerPoint and Excel files",
    "setup.opt.office.a": "Translation itself never needs it, but the side-by-side page preview of Office files uses LibreOffice.",
    "setup.opt.office.link": "Download LibreOffice ↗",
    "setup.opt.claude.q": "Using Claude instead of Gemini",
    "setup.opt.claude.a": "Higher quality for legal and financial text, but paid. Install the extra below, then pick Claude in the sidebar and add your Anthropic key.",
    "setup.fix.title": "Troubleshooting",
    "setup.fix.unreach.q": "\"Couldn't reach the server\"",
    "setup.fix.unreach.a": "The server from step 3 isn't running, or this page is pointed at the wrong address. Start it again, then check the **Server address** field in the sidebar matches what the terminal printed.",
    "setup.fix.notfound.q": "\"palimpsest: command not found\"",
    "setup.fix.notfound.a": "Python's scripts folder isn't on your PATH. Run `python -m palimpsest serve` instead -- it does the same thing.",
    "setup.fix.port.q": "\"Address already in use\"",
    "setup.fix.port.a": "Something else is using port 8765, often an older palimpsest window you forgot about. Close it, or start on another port with `--port 8800` and update the Server address in the sidebar.",
    "setup.fix.key.q": "My key won't save, or says it doesn't work",
    "setup.fix.key.a": "Copy the whole key with no spaces around it. The sidebar can only save it once the server is reachable -- fix the connection first, then paste it again.",
    "setup.fix.scan.q": "A scanned document came back mostly untranslated",
    "setup.fix.scan.a": "Check that OCR is installed (see Optional extras). Very small print on a scan is also skipped on purpose; the Results page lists everything that didn't translate.",
    "setup.done": "Back to home",
    "setup.issues": "Still stuck? Open an issue ↗",

    "theme.toggle": "Toggle color theme",

    "lang.switchTo": "Switch to {lang}",
    "lang.english": "English",
    "lang.spanish": "Spanish",

    "zoom.out": "Zoom out",
    "zoom.in": "Zoom in",
    "zoom.reset": "Reset zoom",

    "wipe.aria": "Compare original and translated page",
    "wipe.source": "source",
    "wipe.translated": "translated",

    "rail.backend": "Backend",
    "rail.hideSidebar": "Hide sidebar",
    "rail.protectedEntities": "Protected entities",
    "rail.group.companies": "Companies",
    "rail.group.people": "People",
    "rail.group.places": "Places",
    "rail.group.other": "Other",
    "rail.dropHere": "drop here",
    "rail.moveTo": "Move to {group}",
    "rail.addPlaceholder": "Add a name, press Enter...",
    "rail.add": "Add",
    "rail.removeAria": "Remove {value}",
    "rail.caseNote": "Case and accent variants are generated for you -- add `Banco Litoral`, not `Banco Litoral` and `BANCO LITORAL` separately.",
    "rail.importToml": "Import .toml",
    "rail.exportToml": "Export .toml",
    "rail.importNotice": "Prototype only -- the real build parses a dropped .toml in the same shape as private/entities.toml.",
    "rail.removeAll": "Remove all",
    "rail.removedAllNotice": "All protected entities removed.",
    "rail.undo": "Undo",
    "rail.profiles": "Profiles",
    "rail.noProfiles": "No saved profiles yet.",
    "rail.profileNamePlaceholder": "Profile name...",
    "rail.saveProfile": "Save",
    "rail.saveProfileAria": "Save profile",
    "rail.profileSaved": "Saved as “{name}”.",
    "rail.loadProfile": "Load profile: {name}",
    "rail.deleteProfile": "Delete profile: {name}",
    "rail.suggested": "Suggested, from the document",
    "rail.suggestedNote": "Capitalized phrases found in the document that aren't protected yet. Nothing here is applied automatically.",

    "backend.apiKeyLabel": "API key",
    "backend.check": "Check",
    "backend.status.idle": "Not checked yet",
    "backend.status.checking": "Checking...",
    "backend.status.ok": "Key works -- gemini-3.5-flash-lite reachable",
    "backend.status.empty": "Enter a key first",
    "backend.keyNote": "Held for this browser session and sent to your own local server only -- never written to disk, never sent anywhere but the backend you picked.",
    "backend.getKey": "Get a free Gemini key ↗",
    "backend.keyDetected": "detected",
    "backend.keyServerNote": "Sent only to the server address above and saved there (its own .env file) -- never anywhere else.",
    "backend.keyChange": "change API key",
    "backend.keyForget": "forget saved key",
    "backend.keyCachedLocally": "Saved in this browser -- will be sent to your server as soon as it's reachable.",
    "backend.keyEntrySave": "Save",
    "backend.keyEntrySaving": "Saving...",
    "backend.keyEntryError": "Couldn't save the key -- check the server address above and try again.",
    "backend.keyEntryHint": "Saved in this browser, and sent to the server at the address above (its own `.env` file) once it's reachable -- never anywhere else. You can also set `{envVar}` yourself.",
    "backend.cancel": "cancel",
    "backend.healthUnreachable": "Can't reach the server -- start it with `palimpsest serve`.",
    "backend.recheck": "Recheck",
    "backend.serverAddress": "Server address",
    "backend.serverAddressSameOrigin": "this page",
    "backend.serverAddressChange": "change",
    "backend.serverAddressSave": "Save",
    "backend.sub.gemini": "Free tier - needs a free API key",
    "backend.sub.translatepy": "Free - no key - offline-friendly fallback",
    "backend.sub.anthropic": "Paid - best quality on legal & financial prose",
    "backend.sub.google": "Free - no key - no entity or glossary awareness",

    "compare.back": "← Back to results",
    "compare.prevAria": "Previous page",
    "compare.nextAria": "Next page",
    "compare.page": "page {n} of {total}",
    "compare.compare": "Compare",
    "compare.edit": "Edit",
    "compare.fixtureNote": "The sample fixture covers page 1 only -- page navigation above is cosmetic in this prototype.",
    "compare.loadingLayout": "Loading page layout...",

    "overview.eyebrow": "How it works",
    "overview.title": "Documents, translated in place.",
    "overview.body": "palimpsest translates PDFs and Office files without rebuilding them -- same pages, same fonts, same artwork, only the words change. Anything you list as protected, a company name, a person, an amount, stays exactly as written.",
    "overview.step1": "**Pick a backend.** Gemini's free tier needs only an API key, no billing setup -- see the sidebar.",
    "overview.step2": "**Name what must survive verbatim.** Company names, people, places -- added once, protected everywhere.",
    "overview.step3": "**Drop a file.** PDF, Word, PowerPoint, or Excel -- you get back a replica, plus an honest report of anything that didn't translate.",
    "overview.cta": "See a sample →",
    "overview.dropTitle": "Drop a file here to start now",
    "overview.dropExts": ".pdf · .docx · .pptx · .xlsx",
    "overview.helpAria": "Open the setup instructions",
    "overview.helpTitle": "Stuck? Seeing a server error?",
    "overview.helpBody": "palimpsest runs on your own computer, so it needs a few minutes of one-time setup. We'll walk you through it in four short steps.",
    "overview.helpCta": "Get unstuck",

    "sample.back": "← Back to home",
    "sample.caption": "drag, or use ← → -- Aurora Plaza Trust, sample deed, 1 of 1",
    "sample.dropTitle": "Drop files here, or click to browse",
    "sample.dropSub": ".pdf · .docx · .pptx · .xlsx -- dropped anywhere on this page",
    "sample.altOut": "Translated sample page (English)",
    "sample.altSrc": "Original sample page (Spanish)",

    "queue.title": "Queue",
    "queue.body": "Classified before anything is sent anywhere -- a scan means an OCR pass, which is the slow part. Pick the language each file should be translated into.",
    "queue.kind.digital": "digital",
    "queue.kind.scan": "scan",
    "queue.kind.ocr": "OCR text layer",
    "queue.kind.office": "office document",
    "queue.pagesUnit": "{n} pages",
    "queue.translateTo": "Translate to",
    "queue.translateToAria": "Target language for {name}",
    "queue.removeAria": "Remove {name}",
    "queue.scanAlert": "**{name}** is a scan -- it needs OCR before translation, which runs as an external process and can take several minutes with no way to interrupt it once started.",
    "queue.cta": "Estimate cost →",

    "estimate.title": "Before anything is spent",
    "estimate.body": "Nothing is sent to a translation backend until you confirm here.",
    "estimate.paragraphs": "Paragraphs",
    "estimate.uniqueStrings": "{n} unique strings",
    "estimate.cacheHits": "Cache hits",
    "estimate.cacheSub": "0% -- first run of this document",
    "estimate.tokens": "Tokens (est.)",
    "estimate.in": "in",
    "estimate.out": "out",
    "estimate.cost": "Cost",
    "estimate.costSub": "estimated, not exact",
    "estimate.costUnknown": "unknown",
    "estimate.note": "Cost shown as unknown, not $0.00, whenever the backend can't price the request -- Google Translate is free by design, not free by omission.",
    "estimate.allScansBody": "**Every file here is a scan.** There's no text layer to count yet, and the OCR pass that creates one runs during translation, not at this step. Paragraphs, tokens, and cost all stay unknown until then -- translation itself works fine, the numbers just can't be known in advance.",
    "estimate.scanExcluded": "{n} scanned files aren't counted above -- they have no text layer until OCR runs during translation.",
    "estimate.scanExcludedSingular": "{n} scanned file isn't counted above -- it has no text layer until OCR runs during translation.",
    "estimate.cta": "Translate {n} documents →",
    "estimate.ctaSingular": "Translate {n} document →",
    "estimate.cancelBlockingJob": "Cancel that job and start this one",

    "running.title": "Running",
    "running.phase.classify.name": "Classify",
    "running.phase.classify.detail": "digital text layer found",
    "running.phase.ocr.name": "OCR",
    "running.phase.ocr.detail": "skipped -- not a scan",
    "running.phase.extract.name": "Extract",
    "running.phase.extract.detail": "172 paragraphs found across 4 pages",
    "running.phase.translate.name": "Translate",
    "running.phase.render.name": "Render",
    "running.phase.render.detail": "waiting",
    "running.phase.save.name": "Save",
    "running.phase.save.detail": "waiting",
    "running.translateProgress": "{count} of 154 unique strings",
    "running.translateProgressReal": "{count} of {total} unique strings",
    "running.footer": "document 1 of 2 · {pct}% of this document",
    "running.footerReal": "document {i} of {n} · {pct}% of this document",
    "running.waiting": "waiting",
    "running.connectionLost": "Lost the connection to the server while running -- the job may still be in progress.",
    "running.cancelNote": "Cancelling abandons the result -- an in-flight OCR or translation call can't be interrupted mid-request, only left to finish and discarded.",
    "running.jobFailed": "The job failed -- see the results page for detail.",
    "running.jobLost": "Lost track of this job -- the server may have restarted. Nothing was translated silently; you'll need to start over.",

    "results.titleRest": "of {total} paragraphs translated.",
    "results.noJobTitle": "No results yet",
    "results.noJobBody": "There's no translation to show here -- start one from the overview or sample screen.",
    "results.disclaimer": "Machine translation isn't perfect -- review this document before relying on it, especially names, dates, and figures.",
    "results.fileFailedTitle": "This translation could not be completed",
    "results.viewPages": "View pages",
    "results.newTranslation": "New translation",
    "results.stat.translated": "Translated",
    "results.stat.skippedProtected": "Kept Spanish - protected",
    "results.stat.failed": "Failed",
    "results.stat.refused": "Refused",
    "results.stat.identical": "Identical",
    "results.subtitle1": "What didn't translate",
    "results.status.failed": "failed",
    "results.status.refused": "refused",
    "results.status.skipped": "skipped · protected",
    "results.issue.failed1": "page 2 - entity/number assertion failed twice",
    "results.issue.refused1": "page 3 - model declined to answer",
    "results.issue.failed2": "page 1 - digit-sequence mismatch after retry",
    "results.issue.skipped1": "page 1 - matches a protected entity, left untouched by design",
    "results.viewOnPage": "View on page →",
    "results.noIssues": "Nothing to report -- every paragraph translated cleanly.",
    "results.subtitle2": "Font substitutions",
    "results.fontSubCount": "{count} paragraphs",
    "results.download.replica.title": "Replica",
    "results.download.replica.sub": "trust-deed-aurora.en.pdf",
    "results.download.dual.title": "Dual PDF",
    "results.download.dual.sub": "source + translated, interleaved",
    "results.download.report.title": "Report",
    "results.download.report.sub": "trust-deed-aurora.report.json",
    "results.downloadNotice": "Prototype only -- would download {file}",

    "edit.deleteParagraph": "Delete paragraph",
    "edit.paragraphLabel": "Paragraph {n}",
    "edit.editingSuffix": " - editing text",
    "edit.noneSelected": "No paragraph selected",
    "edit.paragraphAria": "Paragraph {n} of {total}, page 1",
    "edit.unsavedCount": "{n} unsaved edit",
    "edit.unsavedCountPlural": "{n} unsaved edits",
    "edit.noUnsaved": "No unsaved edits",
    "edit.discard": "Discard edits",
    "edit.download": "Download edits (JSON)",
    "edit.discardNotice": "All edits discarded.",
    "edit.exportNotice": "Prototype only -- the real build PATCHes this to /api/jobs/{id}/layout.",
    "edit.exportNoticeReal": "Saved -- the PDF has been regenerated with your edits.",
    "edit.deleteNotice": "Paragraph removed -- undoable below.",
    "edit.restoreNotice": "Paragraph restored.",
    "edit.restore": "removed - click to restore",
    "edit.capacity.overflow": "will overflow -- the server draws it anyway",
    "edit.capacity.shrunk": "will shrink to {size}pt (from {from}pt)",
    "edit.capacity.fits": "fits - {n} line",
    "edit.capacity.fitsPlural": "fits - {n} lines",
    "edit.capacity.estimatedSuffix": " - estimated",
  },
  es: {
    "common.chooseFiles": "Elegir archivos",
    "common.back": "← Volver",
    "common.cancel": "Cancelar",
    "common.undo": "Deshacer",
    "common.step1": "Paso 1 de 3",
    "common.step2": "Paso 2 de 3",
    "common.step3": "Paso 3 de 3",

    "app.toggleSettings": "Alternar ajustes",
    "app.brandAria": "Ir al resumen",
    "app.showSidebar": "Mostrar barra lateral",
    "app.backendUnreachable": "No se pudo conectar con el servidor",
    "app.serverUnreachableBody": "Ningún servidor local responde en la dirección de la barra lateral. Inícialo con `{cmd}`.",
    "app.setupHintTitle": "Configura un backend primero",
    "app.setupHintBody": "Todavía no hay ningún servidor disponible. Abre la barra lateral y elige un backend -- el nivel gratuito de Gemini solo necesita una clave de API, sin configurar facturación -- y vuelve a intentarlo.",

    "app.setupLink": "Instrucciones de configuración →",

    "footer.github": "GitHub ↗",
    "footer.pypi": "PyPI ↗",
    "footer.license": "Apache 2.0 ↗",

    "setup.back": "← Volver al inicio",
    "setup.eyebrow": "Guía de configuración",
    "setup.title": "Pon palimpsest en marcha en cuatro pasos.",
    "setup.intro": "palimpsest se ejecuta en tu propio equipo, así que tus documentos no salen de él salvo hacia el servicio de traducción que elijas. Eso implica unos minutos de configuración inicial. Hazlo una vez y listo.",
    "setup.copy": "Copiar",
    "setup.copied": "Copiado",
    "setup.s1.title": "Instala Python 3.11 o superior",
    "setup.s1.body": "Comprueba qué versión tienes con `python --version`. En Windows, marca **Add Python to PATH** en el instalador -- casi todos los errores de \"comando no encontrado\" vienen de omitirlo.",
    "setup.s1.link": "Descargar Python ↗",
    "setup.s2.title": "Instala palimpsest",
    "setup.s2.body": "Abre una terminal (Símbolo del sistema, PowerShell o Terminal) y ejecuta esto. Instala el servidor y el backend gratuito de Gemini.",
    "setup.s3.title": "Inicia el servidor local",
    "setup.s3.body": "Ejecútalo y **deja la ventana abierta** -- esa ventana es el servidor. Si la cierras, palimpsest se detiene.",
    "setup.s3.note": "Escucha en http://127.0.0.1:8765, accesible solo desde tu propio equipo.",
    "setup.s4.title": "Añade una clave gratuita de Gemini",
    "setup.s4.body": "Obtén una clave gratuita en Google AI Studio (sin facturación ni tarjeta), pégala en el cuadro **Clave de API** de la barra lateral y pulsa Guardar.",
    "setup.check.title": "¿Funciona?",
    "setup.check.idle": "Cuando el servidor esté en marcha, comprueba la conexión desde aquí.",
    "setup.check.ok": "Conectado -- el servidor responde. Ya puedes traducir.",
    "setup.check.fail": "Sigue sin responder. Asegúrate de que la ventana del paso 3 esté abierta y vuelve a comprobar.",
    "setup.check.btn": "Comprobar conexión",
    "setup.opt.title": "Extras opcionales",
    "setup.opt.intro": "Ninguno hace falta para una primera traducción. Añádelos cuando te encuentres con la situación que resuelven.",
    "setup.opt.ocr.q": "Traducir PDFs escaneados",
    "setup.opt.ocr.a": "Un escaneo no tiene texto que leer, así que palimpsest ejecuta OCR primero. Instala el extra de abajo, más **Tesseract** con los datos de idioma de tus documentos (`spa` para español, `eng` para inglés), y asegúrate de que `tesseract` esté en tu PATH.",
    "setup.opt.office.q": "Vista previa de archivos Word, PowerPoint y Excel",
    "setup.opt.office.a": "La traducción en sí nunca lo necesita, pero la vista previa lado a lado de archivos de Office usa LibreOffice.",
    "setup.opt.office.link": "Descargar LibreOffice ↗",
    "setup.opt.claude.q": "Usar Claude en lugar de Gemini",
    "setup.opt.claude.a": "Mayor calidad para textos legales y financieros, pero de pago. Instala el extra de abajo, elige Claude en la barra lateral y añade tu clave de Anthropic.",
    "setup.fix.title": "Solución de problemas",
    "setup.fix.unreach.q": "\"No se pudo conectar con el servidor\"",
    "setup.fix.unreach.a": "El servidor del paso 3 no está en marcha, o esta página apunta a una dirección equivocada. Vuelve a iniciarlo y comprueba que el campo **Dirección del servidor** de la barra lateral coincide con lo que mostró la terminal.",
    "setup.fix.notfound.q": "\"palimpsest: comando no encontrado\"",
    "setup.fix.notfound.a": "La carpeta de scripts de Python no está en tu PATH. Ejecuta `python -m palimpsest serve` -- hace lo mismo.",
    "setup.fix.port.q": "\"Address already in use\"",
    "setup.fix.port.a": "Otro programa usa el puerto 8765, a menudo una ventana antigua de palimpsest. Ciérrala, o inicia en otro puerto con `--port 8800` y actualiza la dirección del servidor en la barra lateral.",
    "setup.fix.key.q": "Mi clave no se guarda, o dice que no funciona",
    "setup.fix.key.a": "Copia la clave completa, sin espacios alrededor. La barra lateral solo puede guardarla cuando el servidor es accesible -- arregla primero la conexión y vuelve a pegarla.",
    "setup.fix.scan.q": "Un documento escaneado salió casi sin traducir",
    "setup.fix.scan.a": "Comprueba que el OCR esté instalado (ver Extras opcionales). El texto muy pequeño de un escaneo también se omite a propósito; la página de Resultados lista todo lo que no se tradujo.",
    "setup.done": "Volver al inicio",
    "setup.issues": "¿Sigues atascado? Abre un issue ↗",

    "theme.toggle": "Cambiar tema de color",

    "lang.switchTo": "Cambiar a {lang}",
    "lang.english": "inglés",
    "lang.spanish": "español",

    "zoom.out": "Alejar",
    "zoom.in": "Acercar",
    "zoom.reset": "Restablecer zoom",

    "wipe.aria": "Comparar la página original y la traducida",
    "wipe.source": "original",
    "wipe.translated": "traducido",

    "rail.backend": "Backend",
    "rail.hideSidebar": "Ocultar barra lateral",
    "rail.protectedEntities": "Entidades protegidas",
    "rail.group.companies": "Empresas",
    "rail.group.people": "Personas",
    "rail.group.places": "Lugares",
    "rail.group.other": "Otros",
    "rail.dropHere": "soltar aquí",
    "rail.moveTo": "Mover a {group}",
    "rail.addPlaceholder": "Agrega un nombre y presiona Enter...",
    "rail.add": "Agregar",
    "rail.removeAria": "Quitar {value}",
    "rail.caseNote": "Las variantes de mayúsculas y acentos se generan automáticamente -- agrega `Banco Litoral`, no `Banco Litoral` y `BANCO LITORAL` por separado.",
    "rail.importToml": "Importar .toml",
    "rail.exportToml": "Exportar .toml",
    "rail.importNotice": "Solo prototipo -- la versión real analiza un .toml soltado con la misma forma que private/entities.toml.",
    "rail.removeAll": "Quitar todo",
    "rail.removedAllNotice": "Se quitaron todas las entidades protegidas.",
    "rail.undo": "Deshacer",
    "rail.profiles": "Perfiles",
    "rail.noProfiles": "Aún no hay perfiles guardados.",
    "rail.profileNamePlaceholder": "Nombre del perfil...",
    "rail.saveProfile": "Guardar",
    "rail.saveProfileAria": "Guardar perfil",
    "rail.profileSaved": "Guardado como “{name}”.",
    "rail.loadProfile": "Cargar perfil: {name}",
    "rail.deleteProfile": "Eliminar perfil: {name}",
    "rail.suggested": "Sugerido, del documento",
    "rail.suggestedNote": "Frases con mayúscula inicial encontradas en el documento que aún no están protegidas. Nada aquí se aplica automáticamente.",

    "backend.apiKeyLabel": "Clave de API",
    "backend.check": "Verificar",
    "backend.status.idle": "Aún no verificada",
    "backend.status.checking": "Verificando...",
    "backend.status.ok": "La clave funciona -- gemini-3.5-flash-lite accesible",
    "backend.status.empty": "Primero ingresa una clave",
    "backend.keyNote": "Se guarda solo durante esta sesión del navegador y se envía únicamente a tu propio servidor local -- nunca se escribe en disco ni se envía a otro lugar que no sea el backend elegido.",
    "backend.getKey": "Obtener una clave gratuita de Gemini ↗",
    "backend.keyDetected": "detectada",
    "backend.keyServerNote": "Se envía solo a la dirección del servidor de arriba y se guarda ahí (su propio archivo .env) -- nunca a ningún otro lugar.",
    "backend.keyChange": "cambiar clave de API",
    "backend.keyForget": "olvidar clave guardada",
    "backend.keyCachedLocally": "Guardada en este navegador -- se enviará a tu servidor en cuanto esté disponible.",
    "backend.keyEntrySave": "Guardar",
    "backend.keyEntrySaving": "Guardando...",
    "backend.keyEntryError": "No se pudo guardar la clave -- verifica la dirección del servidor de arriba e inténtalo de nuevo.",
    "backend.keyEntryHint": "Guardada en este navegador, y enviada al servidor de la dirección de arriba (su propio archivo `.env`) en cuanto esté disponible -- nunca a ningún otro lugar. También puedes configurar `{envVar}` tú mismo.",
    "backend.cancel": "cancelar",
    "backend.healthUnreachable": "No se puede conectar con el servidor -- inícialo con `palimpsest serve`.",
    "backend.recheck": "Volver a comprobar",
    "backend.serverAddress": "Dirección del servidor",
    "backend.serverAddressSameOrigin": "esta página",
    "backend.serverAddressChange": "cambiar",
    "backend.serverAddressSave": "Guardar",
    "backend.sub.gemini": "Nivel gratuito - requiere una clave de API gratuita",
    "backend.sub.translatepy": "Gratis - sin clave - alternativa sin conexión",
    "backend.sub.anthropic": "De pago - mejor calidad en prosa legal y financiera",
    "backend.sub.google": "Gratis - sin clave - sin reconocimiento de entidades ni glosario",

    "compare.back": "← Volver a resultados",
    "compare.prevAria": "Página anterior",
    "compare.nextAria": "Página siguiente",
    "compare.page": "página {n} de {total}",
    "compare.compare": "Comparar",
    "compare.edit": "Editar",
    "compare.fixtureNote": "La muestra de prueba solo cubre la página 1 -- la navegación de páginas de arriba es solo decorativa en este prototipo.",
    "compare.loadingLayout": "Cargando el diseño de la página...",

    "overview.eyebrow": "Cómo funciona",
    "overview.title": "Documentos, traducidos en el mismo lugar.",
    "overview.body": "palimpsest traduce PDFs y archivos de Office sin reconstruirlos -- las mismas páginas, las mismas fuentes, el mismo arte, solo cambian las palabras. Todo lo que marques como protegido, un nombre de empresa, una persona, un monto, se mantiene exactamente como está escrito.",
    "overview.step1": "**Elige un backend.** El nivel gratuito de Gemini solo necesita una clave de API, sin configurar facturación -- consulta la barra lateral.",
    "overview.step2": "**Nombra lo que debe permanecer intacto.** Nombres de empresas, personas, lugares -- se agregan una vez y quedan protegidos en todas partes.",
    "overview.step3": "**Suelta un archivo.** PDF, Word, PowerPoint o Excel -- obtienes una réplica, más un informe honesto de todo lo que no se tradujo.",
    "overview.cta": "Ver una muestra →",
    "overview.dropTitle": "Suelta un archivo aquí para empezar ahora",
    "overview.dropExts": ".pdf · .docx · .pptx · .xlsx",
    "overview.helpAria": "Abrir las instrucciones de configuración",
    "overview.helpTitle": "¿Atascado? ¿Ves un error de servidor?",
    "overview.helpBody": "palimpsest se ejecuta en tu propio equipo, así que necesita unos minutos de configuración inicial. Te guiamos en cuatro pasos cortos.",
    "overview.helpCta": "Resolverlo",

    "sample.back": "← Volver al inicio",
    "sample.caption": "arrastra, o usa ← → -- Fideicomiso Aurora Plaza, escritura de muestra, 1 de 1",
    "sample.dropTitle": "Suelta archivos aquí, o haz clic para buscar",
    "sample.dropSub": ".pdf · .docx · .pptx · .xlsx -- soltado en cualquier parte de esta página",
    "sample.altOut": "Página de muestra traducida (inglés)",
    "sample.altSrc": "Página de muestra original (español)",

    "queue.title": "Cola",
    "queue.body": "Clasificado antes de enviar nada a ningún lado -- un escaneo implica un paso de OCR, que es la parte lenta. Elige el idioma al que se traducirá cada archivo.",
    "queue.kind.digital": "digital",
    "queue.kind.scan": "escaneo",
    "queue.kind.ocr": "capa de texto OCR",
    "queue.kind.office": "documento de office",
    "queue.pagesUnit": "{n} páginas",
    "queue.translateTo": "Traducir a",
    "queue.translateToAria": "Idioma de destino para {name}",
    "queue.removeAria": "Quitar {name}",
    "queue.scanAlert": "**{name}** es un escaneo -- necesita OCR antes de traducirse, lo cual se ejecuta como un proceso externo y puede tardar varios minutos sin forma de interrumpirlo una vez iniciado.",
    "queue.cta": "Estimar costo →",

    "estimate.title": "Antes de gastar nada",
    "estimate.body": "Nada se envía a un backend de traducción hasta que confirmes aquí.",
    "estimate.paragraphs": "Párrafos",
    "estimate.uniqueStrings": "{n} cadenas únicas",
    "estimate.cacheHits": "Aciertos de caché",
    "estimate.cacheSub": "0% -- primera ejecución de este documento",
    "estimate.tokens": "Tokens (est.)",
    "estimate.in": "entrada",
    "estimate.out": "salida",
    "estimate.cost": "Costo",
    "estimate.costSub": "estimado, no exacto",
    "estimate.costUnknown": "desconocido",
    "estimate.note": "El costo se muestra como desconocido, no $0.00, cuando el backend no puede calcular el precio de la solicitud -- Google Translate es gratis por diseño, no gratis por omisión.",
    "estimate.allScansBody": "**Todos los archivos aquí son escaneos.** Todavía no hay capa de texto que contar, y el paso de OCR que la crea se ejecuta durante la traducción, no en este paso. Los párrafos, los tokens y el costo quedan como desconocidos hasta entonces -- la traducción funciona igual, solo que los números no se pueden saber de antemano.",
    "estimate.scanExcluded": "{n} archivos escaneados no están incluidos arriba -- no tienen capa de texto hasta que el OCR se ejecute durante la traducción.",
    "estimate.scanExcludedSingular": "{n} archivo escaneado no está incluido arriba -- no tiene capa de texto hasta que el OCR se ejecute durante la traducción.",
    "estimate.cta": "Traducir {n} documentos →",
    "estimate.ctaSingular": "Traducir {n} documento →",
    "estimate.cancelBlockingJob": "Cancelar ese trabajo y comenzar este",

    "running.title": "En proceso",
    "running.phase.classify.name": "Clasificar",
    "running.phase.classify.detail": "se encontró capa de texto digital",
    "running.phase.ocr.name": "OCR",
    "running.phase.ocr.detail": "omitido -- no es un escaneo",
    "running.phase.extract.name": "Extraer",
    "running.phase.extract.detail": "172 párrafos encontrados en 4 páginas",
    "running.phase.translate.name": "Traducir",
    "running.phase.render.name": "Renderizar",
    "running.phase.render.detail": "esperando",
    "running.phase.save.name": "Guardar",
    "running.phase.save.detail": "esperando",
    "running.translateProgress": "{count} de 154 cadenas únicas",
    "running.translateProgressReal": "{count} de {total} cadenas únicas",
    "running.footer": "documento 1 de 2 · {pct}% de este documento",
    "running.footerReal": "documento {i} de {n} · {pct}% de este documento",
    "running.waiting": "esperando",
    "running.connectionLost": "Se perdió la conexión con el servidor durante el proceso -- el trabajo podría seguir en curso.",
    "running.cancelNote": "Cancelar descarta el resultado -- una llamada de OCR o traducción en curso no se puede interrumpir a mitad de camino, solo se deja terminar y se descarta.",
    "running.jobFailed": "El trabajo falló -- ver la página de resultados para más detalle.",
    "running.jobLost": "Se perdió el rastro de este trabajo -- el servidor podría haberse reiniciado. No se tradujo nada en silencio; tendrás que empezar de nuevo.",

    "results.titleRest": "de {total} párrafos traducidos.",
    "results.noJobTitle": "Aún no hay resultados",
    "results.noJobBody": "No hay ninguna traducción que mostrar aquí -- inicia una desde la pantalla de inicio o de muestra.",
    "results.disclaimer": "La traducción automática no es perfecta -- revisa este documento antes de confiar en él, especialmente nombres, fechas y cifras.",
    "results.fileFailedTitle": "Esta traducción no se pudo completar",
    "results.viewPages": "Ver páginas",
    "results.newTranslation": "Nueva traducción",
    "results.stat.translated": "Traducidos",
    "results.stat.skippedProtected": "Se mantuvo en español - protegido",
    "results.stat.failed": "Fallidos",
    "results.stat.refused": "Rechazados",
    "results.stat.identical": "Idénticos",
    "results.subtitle1": "Lo que no se tradujo",
    "results.status.failed": "fallido",
    "results.status.refused": "rechazado",
    "results.status.skipped": "omitido · protegido",
    "results.issue.failed1": "página 2 - la verificación de entidad/número falló dos veces",
    "results.issue.refused1": "página 3 - el modelo se negó a responder",
    "results.issue.failed2": "página 1 - discrepancia en la secuencia de dígitos tras reintentar",
    "results.issue.skipped1": "página 1 - coincide con una entidad protegida, dejada intacta a propósito",
    "results.viewOnPage": "Ver en la página →",
    "results.noIssues": "Nada que informar -- todos los párrafos se tradujeron sin problemas.",
    "results.subtitle2": "Sustituciones de fuente",
    "results.fontSubCount": "{count} párrafos",
    "results.download.replica.title": "Réplica",
    "results.download.replica.sub": "trust-deed-aurora.en.pdf",
    "results.download.dual.title": "PDF dual",
    "results.download.dual.sub": "original + traducido, intercalados",
    "results.download.report.title": "Informe",
    "results.download.report.sub": "trust-deed-aurora.report.json",
    "results.downloadNotice": "Solo prototipo -- descargaría {file}",

    "edit.deleteParagraph": "Eliminar párrafo",
    "edit.paragraphLabel": "Párrafo {n}",
    "edit.editingSuffix": " - editando texto",
    "edit.noneSelected": "Ningún párrafo seleccionado",
    "edit.paragraphAria": "Párrafo {n} de {total}, página 1",
    "edit.unsavedCount": "{n} edición sin guardar",
    "edit.unsavedCountPlural": "{n} ediciones sin guardar",
    "edit.noUnsaved": "Sin ediciones pendientes",
    "edit.discard": "Descartar ediciones",
    "edit.download": "Descargar ediciones (JSON)",
    "edit.discardNotice": "Todas las ediciones fueron descartadas.",
    "edit.exportNotice": "Solo prototipo -- la versión real hace PATCH a /api/jobs/{id}/layout.",
    "edit.exportNoticeReal": "Guardado -- el PDF fue regenerado con tus ediciones.",
    "edit.deleteNotice": "Párrafo eliminado -- se puede deshacer abajo.",
    "edit.restoreNotice": "Párrafo restaurado.",
    "edit.restore": "eliminado - clic para restaurar",
    "edit.capacity.overflow": "desbordará -- el servidor lo dibuja de todas formas",
    "edit.capacity.shrunk": "se reducirá a {size}pt (desde {from}pt)",
    "edit.capacity.fits": "cabe - {n} línea",
    "edit.capacity.fitsPlural": "cabe - {n} líneas",
    "edit.capacity.estimatedSuffix": " - estimado",
  },
};
